steps:
  # 環境変数は$ではなく$$で参照する。/Environment variables are referenced by $$, not $.
  # $はCloud Buildの変数を置換するために使われる。/$ is used to substitute Cloud Build variables.
  # pnpm install, build
  - name: "node:21"
    id: 'pnpm install and build'
    entrypoint: "bash"
    env:
      - "FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID}"
      - "NEXT_PUBLIC_FIREBASE_API_KEY=${_NEXT_PUBLIC_FIREBASE_API_KEY}"
      - "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}"
      - "NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_NEXT_PUBLIC_FIREBASE_PROJECT_ID}"
      - "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}"
      - "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}"
      - "NEXT_PUBLIC_FIREBASE_APP_ID=${_NEXT_PUBLIC_FIREBASE_APP_ID}"
      - "NEXT_PUBLIC_MEASUREMENT_ID=${_NEXT_PUBLIC_MEASUREMENT_ID}"
    args:
      - '-c'
      - |
        echo "Installing pnpm..."
        npm install -g pnpm
        echo "pnpm installed successfully."
        echo "Running pnpm install..."
        pnpm install --frozen-lockfile && \
        echo "pnpm install completed." && \
        echo "Running pnpm run build..." && \
        pnpm run build && \
        echo "pnpm run build completed."

  # Firebase Deploy
  - name: gcr.io/${PROJECT_ID}/firebase
    entrypoint: "sh"
    args:
      - "-c"
      - |
        firebase experiments:enable webframeworks && \
        firebase deploy --project=$_FIREBASE_PROJECT_ID --only=hosting

options:
  logging: CLOUD_LOGGING_ONLY
